# docker-compose.dev.yml
version: "3.8"

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000" # Fixed port for development
  #   environment:
  #     DATABASE_URL: postgres://postgres:password@db:5432/mydatabase
  #   depends_on:
  #     - db
  #   env_file:
  #     - .env
  #   volumes:
  #     - .:/app # Mounts the current directory to /app in the container
  #   command: bun dev

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
